output:
	
	gcc external/cat.c -o cat.o
	gcc external/cat-n.c -o cat-n.o
	gcc external/cat-b.c -o cat-b.o
	gcc external/date.c -o date.o
	gcc external/date-u.c -o date-u.o
	gcc external/date-R.c -o date-R.o
	gcc external/ls.c -o ls.o
	gcc external/ls-a.c -o ls-a.o
	gcc external/ls-A.c -o ls-A.o
	gcc external/mkdir.c -o mkdir.o
	gcc external/mkdir-m.c -o mkdir-m.o
	gcc external/mkdir-v.c -o mkdir-v.o
	gcc external/rm.c -o rm.o
	gcc external/rm-f.c -o rm-f.o
	gcc external/rm-v.c -o rm-v.o
	
	gcc shell.c -o shell.out -pthread

clean:
	rm *.o shell.out
